### PR TITLE
Feat/add cluster

### PR DESCRIPTION
**Pull request by fer1592**

### CODE REVIEW

**Comment by fer1592** [comment]
Instrumented test can be found in the following link:
- https://github.com/fer1592/k8s-android-console/tree/feat/add-cluster/androidTest-results/15-05-2022
- Path: `androidTest-results/15-05-2022`

**Comment by fer1592** [comment]
@AndresGarciaSobrado91 approve?

**Comment by fer1592** [comment]
Not approved?

**Comment by AndresGarciaSobrado91** [comment]
wachin jaja sorry ni abro mi mail ultimamente

**Review by AndresGarciaSobrado91 — APPROVED** [review]
Approved. Will play with your code, especially with the VM variables like LiveData. I think it is getting messy and it needs a cleanup. Maybe some code refactor to have some data class per VM that holds all the navigations and other stuff inside, that can be used as view-state by the fragments. N I C E   J O B 💪

**Pull request merged**
